spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:7432/ewm-main
    username: main
    password: main
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        transaction:
          INFO: INFO
          interceptor: TRACE
        orm:
          jpa:
            INFO: INFO
            JpaTransactionManager: DEBUG
        web: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    org.springframework.web.client.RestTemplate: DEBUG

server:
  port: 8080
