spring:
  datasource:
    url: jdbc:postgresql://localhost:8432/ewm-user-db
    driverClassName: org.postgresql.Driver
    username: user
    password: user
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update #create #none
    properties:
      hibernate:
        format_sql: true
  application:
    name: user-service

server:
  port: 0
