spring:
  datasource:
    url: jdbc:postgresql://localhost:9432/ewm-request-db
    driverClassName: org.postgresql.Driver
    username: request
    password: request
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update #create #none
    properties:
      hibernate:
        format_sql: true
  application:
    name: request-service

server:
  port: 0

grpc:
  client:
    collector:
      address: 'discovery:///collector'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plainText