spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:

        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
          order: 1

        - id: main_service_route
          uri: lb://main-service
          predicates:
            - Path=/**
          order: 2